// invoices_screen.dart — the books, on a phone.
//
// Lists what the business billed and what it paid, and adds a supplier invoice
// from a photo. The photo is the point: the office is holding a paper invoice,
// and typing it in is the part they would rather not do.
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import '../../api.dart';
import '../../i18n.dart';
import '../../theme.dart';
import '../../widgets.dart';
import 'invoice_form_screen.dart';

class InvoicesScreen extends StatefulWidget {
  const InvoicesScreen({super.key});

  @override
  State<InvoicesScreen> createState() => _InvoicesScreenState();
}

class _InvoicesScreenState extends State<InvoicesScreen> {
  // Expenses first: that is the side a photo of a paper invoice belongs to,
  // and income is generated by the app itself from delivered orders.
  String _direction = 'expense';
  // Null means every month / every year, which is what the office wants when
  // hunting for one invoice and does not remember when it was.
  int? _year = DateTime.now().year;
  int? _month;
  List<dynamic> _rows = [];
  bool _loading = true;
  Object? _error;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final data = await api.get('/invoices/', query: {
        'direction': _direction,
        if (_year != null) 'year': '$_year',
        if (_month != null) 'month': '$_month',
      });
      final rows = data is Map ? (data['results'] ?? []) : data;
      if (mounted) setState(() => _rows = rows as List<dynamic>);
    } catch (e) {
      if (mounted) setState(() => _error = e);
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _add() async {
    final made = await Navigator.of(context).push<bool>(
        MaterialPageRoute(builder: (_) => const InvoiceFormScreen()));
    if (made == true) _load();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(t('Invoices'))),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _add,
        backgroundColor: kBlue,
        icon: const Icon(Icons.photo_camera_outlined),
        label: Text(t('Add invoice')),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
            child: SegmentedButton<String>(
              segments: [
                ButtonSegment(value: 'expense', label: Text(t('Paid out'))),
                ButtonSegment(value: 'income', label: Text(t('Billed'))),
              ],
              selected: {_direction},
              onSelectionChanged: (s) {
                setState(() => _direction = s.first);
                _load();
              },
            ),
          ),
          _filters(),
          Expanded(child: _body()),
        ],
      ),
    );
  }

  /// Year and month, side by side. The books are read a month at a time --
  /// that is how the accountant asks for them -- so the period is a first
  /// class control rather than something buried in a search box.
  Widget _filters() {
    final now = DateTime.now().year;
    final years = [for (var y = now; y >= now - 5; y--) y];
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 8, 16, 8),
      child: Row(children: [
        Expanded(
          child: DropdownButtonFormField<int?>(
            initialValue: _year,
            isExpanded: true,
            decoration: InputDecoration(
              labelText: t('Year'),
              isDense: true,
              contentPadding:
                  const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
              border:
                  OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
            ),
            items: [
              DropdownMenuItem(value: null, child: Text(t('All years'))),
              for (final y in years)
                DropdownMenuItem(value: y, child: Text('$y')),
            ],
            onChanged: (v) {
              setState(() => _year = v);
              _load();
            },
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: DropdownButtonFormField<int?>(
            initialValue: _month,
            isExpanded: true,
            decoration: InputDecoration(
              labelText: t('Month'),
              isDense: true,
              contentPadding:
                  const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
              border:
                  OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
            ),
            items: [
              DropdownMenuItem(value: null, child: Text(t('All months'))),
              for (var m = 1; m <= 12; m++)
                DropdownMenuItem(
                    value: m,
                    child: Text(DateFormat.MMMM(Intl.getCurrentLocale())
                        .format(DateTime(2000, m)))),
            ],
            onChanged: (v) {
              setState(() => _month = v);
              _load();
            },
          ),
        ),
      ]),
    );
  }

  Widget _body() {
    if (_loading) return const Center(child: CircularProgressIndicator());
    if (_error != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(mainAxisSize: MainAxisSize.min, children: [
            Text('$_error', textAlign: TextAlign.center,
                style: const TextStyle(color: kDanger)),
            const SizedBox(height: 12),
            OutlinedButton(onPressed: _load, child: Text(t('Try again'))),
          ]),
        ),
      );
    }
    if (_rows.isEmpty) {
      return EmptyState(Icons.receipt_long_outlined, t('No invoices yet.'));
    }
    return RefreshIndicator(
      onRefresh: _load,
      child: ListView.separated(
        padding: const EdgeInsets.all(16),
        itemCount: _rows.length,
        separatorBuilder: (_, _) => const SizedBox(height: 8),
        itemBuilder: (_, i) => _tile(_rows[i] as Map),
      ),
    );
  }

  Widget _tile(Map row) {
    final paid = row['status'] == 'paid';
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: kCard,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: kLine),
      ),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  (row['party_name'] ?? row['client_name'] ?? '').toString(),
                  style: const TextStyle(
                      fontWeight: FontWeight.w700, color: kInk, fontSize: 15),
                ),
                const SizedBox(height: 2),
                Text(
                  [row['number'], row['issued_at'], row['category']]
                      .where((v) => (v ?? '').toString().isNotEmpty)
                      .join(' · '),
                  style: const TextStyle(color: kMuted, fontSize: 12),
                ),
              ],
            ),
          ),
          const SizedBox(width: 10),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Text('₪${row['total'] ?? '0.00'}',
                  style: const TextStyle(
                      fontWeight: FontWeight.w700, color: kInk, fontSize: 15)),
              const SizedBox(height: 4),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                decoration: BoxDecoration(
                  color: (paid ? kSuccess : kWarn).withValues(alpha: .12),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(paid ? t('Paid') : t('Unpaid'),
                    style: TextStyle(
                        color: paid ? kSuccess : kWarn,
                        fontSize: 11,
                        fontWeight: FontWeight.w600)),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
